#!/usr/bin/env python3
"""
check_sis.py — structural checker for SIS #02.   DO NOT EDIT THIS FILE.

    cd sis-02
    python tests/check_sis.py            # human-readable, ends with a SUMMARY line
    python tests/check_sis.py --json     # machine-readable, for the grading pipeline

It checks SHAPE, never QUALITY. It reads report.md and the two PlantUML files in models/:
that the sections, stories, criteria, tables and four AI exchanges are there, that the
prompts are the ones the assignment gives, and that the rules R1-R5 are visible in the
diagrams. It cannot tell whether your model is good, whether a walkthrough is honest or
whether a source says what you claim. Those are graded by a person.

Verdicts:
    PASS   the check is satisfied
    FAIL   the thing is there but wrong: a word count outside its range, an association
           with no multiplicity, a prompt with a [bracketed field] never replaced
    ERROR  the thing cannot be checked at all: a file missing, a section heading deleted

A FAIL you report honestly in submission.yml costs you nothing extra.
A number you invent costs the whole workflow criterion.

Exit codes: 0 = no FAIL and no ERROR · 1 = at least one FAIL or ERROR ·
            2 = report.md missing · 3 = run from the wrong directory.

Standard library only. Python 3.8 or later.
"""

import argparse
import json
import os
import re
import sys
from datetime import date

REPORT = "report.md"
MODELS = "models"
SEQUENCE = os.path.join(MODELS, "sequence.puml")
CLASSES = os.path.join(MODELS, "classes.puml")
ORIGINAL = os.path.join(MODELS, "original")
IMG = os.path.join(MODELS, "img")

SECTIONS = {
    1: "Scope and assumptions",
    2: "User stories and acceptance criteria",
    3: "Sequence diagram",
    4: "Class diagram",
    5: "Traceability",
    6: "Walkthroughs",
    7: "Review decisions",
    8: "Modeling explanation",
    9: "Reflection",
    10: "Appendix A",
    11: "Appendix B",
    12: "Appendix C",
    13: "Appendix D",
}

EXPLANATION = (200, 300)   # section 8
REFLECTION = (150, 200)    # section 9

STORIES = ("US-01", "US-02", "US-03")
CRITERIA = tuple(f"AC-0{n}" for n in range(1, 7))
RULES = ("R1", "R2", "R3", "R4", "R5")
CASES = ("T1", "T2", "T3", "T4")
REQUIRED_CLASSES = ("Student", "Course", "CourseOffering", "Enrollment")

# The five features the scenario excludes. Section 2 is the approved requirements, so none
# of them may appear there. Section 1 is where you say they are out of scope.
EXCLUDED = (
    ("payments", r"\bpay(ment|ments|s|ing)?\b|\bfees?\b|\btuition\b"),
    ("prerequisites", r"\bprerequisites?\b|\bpre-requisites?\b"),
    ("timetable clashes", r"\bclash(es)?\b|\btimetable conflicts?\b|\bschedule conflicts?\b"),
    ("waiting lists", r"\bwait(ing)?[- ]?lists?\b|\bwaitlist(ed|s)?\b"),
    ("cancellation", r"\bcancel(l?ation|l?ed|l?ing|s)?\b|\bunenrol(l|ment|ls|led)?\b|\bdrop(s|ped|ping)? (a |the )?(course|offering)\b"),
)

EXCHANGES = ("B1", "B2", "B3", "B4")
MIN_RESPONSE_WORDS = {"B1": 150, "B2": 150, "B3": 150, "B4": 100}

# Fixed phrases from Prompts A-D. Each must survive in the prompt you actually sent: they are
# how the checker knows you used the given prompt and not a paraphrase. Case, whitespace and
# the kind of dash are ignored.
ANCHORS = {
    "B1": ("act as a requirements analyst",
           "list uncertainty separately",
           "do not add excluded features or invent university policies"),
    "B2": ("return separate plantuml code blocks for a sequence diagram and a domain class diagram",
           "model final checks and creation as one atomic operation",
           "explain assumptions and any technical lifelines"),
    "B3": ("check message order, guards, state changes, multiplicities and naming",
           "cite the affected rule and model element",
           "separate genuine defects from optional design choices"),
    "B4": ("revise the uml sources using only my accepted review decisions",
           "keep justified existing elements and explain each change",
           "flag any unresolved issue"),
}
BRACKET_FIELDS = {"B1": ("[paste them]", "[paste]"), "B4": ("[list]", "[paste]")}
RULE_NAMES = ("catalog", "capacity", "duplicate", "success", "rejection")

BARE_TOOL_NAMES = {
    "chatgpt", "gpt", "claude", "gemini", "copilot", "github copilot", "deepseek",
    "grok", "mistral", "llama", "qwen", "perplexity", "cursor", "openai", "anthropic",
}
MODEL_HIDDEN = "not displayed"
HAS_DIGIT = re.compile(r"\d")

LOCATOR = re.compile(
    r"(\bp{1,2}\.\s*\d)|(\bpages?\s*\d)|(\bslides?\s*#?\d)|(\bsection\s*\d)|(§\s*\d)"
    r"|(\bch(apter|\.)?\s*\d)|(\bfig(ure|\.)?\s*\d)|(\bexercise\s*\d)|(https?://\S+)",
    re.IGNORECASE,
)
URL = re.compile(r"https?://[^\s|)>\]]+", re.IGNORECASE)
ACCESS_DATE = re.compile(r"(\d{4}-\d{2}-\d{2})|(\baccessed\b)", re.IGNORECASE)
ISO_DATE = re.compile(r"^\d{4}-\d{2}-\d{2}$")

PLACEHOLDER = re.compile(r"\(write here[^)]*\)|\(paste here\)", re.IGNORECASE)
COMMENT = re.compile(r"<!--.*?-->", re.DOTALL)
HEADING = re.compile(r"^##\s+(\d+)\.\s*(.*)$")
FENCE = re.compile(r"^(`{3,}|~{3,})")
IMAGE = re.compile(r"!\[[^\]]*\]\(\s*<?([^)\s>]+)>?(?:\s+\"[^\"]*\")?\s*\)")
STOPWORDS = set("""
a an the and or but if of to in on at for from by with without into onto over under is are was
were be been being it its this that these those they them their there here as not no can could
should would will may might must do does did have has had i me my we our you your he she his her
who whom which what when where why how than then so such very more most less least also only
just about each other some any all both one two three first second new use used using
""".split())

# Sequence-diagram vocabulary. Messages, guards and notes are read for these words; the README
# tells you to use them, so a diagram that follows it needs no luck.
CATALOG = re.compile(r"catalog|browse|offerings|list ?offering|search", re.I)
REQUEST = re.compile(r"regist|enrol", re.I)
CREATE = re.compile(r"create|insert|persist|\bsave|\bstore|\badd ?enrol|new ?enrol", re.I)
STATE = re.compile(r"update|increment|decrement|reserve|\bsave|insert|persist|\bstore", re.I)
CONFIRM = re.compile(r"confirm", re.I)
DUP = re.compile(r"duplicate|already", re.I)
DUP_CHECK = re.compile(r"duplicate|already|exists|is ?enrolled|has ?enrol|find ?enrol|existing", re.I)
FULL = re.compile(r"\bfull\b|no (free |available )?(places?|seats?)|(places?|seats?|available)\w* *(==|=|<=) *0"
                  r"|>= *capacity|== *capacity|capacity reached|at capacity", re.I)
CAPACITY_CHECK = re.compile(r"capacity|availab|places|seats|\bcount|\bfull\b", re.I)
ATOMIC = re.compile(r"atomic|transaction|\block|critical", re.I)
NEGATED = re.compile(r"\b(not|no|isn'?t|non)\s+(a\s+|yet\s+|already\s+)*(full|duplicate|enrolled)\b", re.I)
MANY = re.compile(r"^(\*|0\s*\.\.\s*(\*|n|\w+))$", re.I)


# --------------------------------------------------------------------------- text helpers


def words(text):
    """Words as a reader counts them: tokens with at least one letter or digit."""
    text = COMMENT.sub(" ", text or "")
    text = re.sub(r"[*_`#>|]", " ", text)
    return [t for t in text.split() if re.search(r"[0-9A-Za-zА-Яа-яЁёӘәҒғҚқҢңӨөҰұҮүҺһІі]", t)]


def norm(text):
    text = (text or "").lower()
    text = re.sub(r"[‐-―−]", "-", text)          # every dash is a hyphen
    text = re.sub(r"[‘’“”]", "'", text)
    return re.sub(r"\s+", " ", text).strip()


def key(text):
    """Lowercase, letters and digits only — how names are compared across files."""
    return re.sub(r"[^a-z0-9]", "", (text or "").lower())


def content_words(text):
    return {w for w in re.findall(r"[a-zA-Zа-яА-Я]{5,}", (text or "").lower()) if w not in STOPWORDS}


def shingles(text, n=5):
    toks = re.findall(r"\w+", (text or "").lower())
    return {" ".join(toks[i:i + n]) for i in range(max(0, len(toks) - n + 1))}


def share(part, whole_text):
    """What fraction of `part`'s shingles also occur in `whole_text`."""
    if not part:
        return 0.0
    return len(part & shingles(whole_text)) / len(part)


def read(path):
    try:
        with open(path, encoding="utf-8", errors="replace") as handle:
            return handle.read()
    except OSError:
        return None


def split_sections(text):
    """{number: body} for every `## N.` heading outside a code block, comments removed."""
    text = COMMENT.sub("", text)
    found, order, current, buf, in_fence = {}, [], None, [], None
    for line in text.splitlines():
        fence = FENCE.match(line.strip())
        if fence:
            mark = fence.group(1)
            if in_fence is None:
                in_fence = mark
            elif mark[0] == in_fence[0] and len(mark) >= len(in_fence) and line.strip() == mark:
                in_fence = None
        m = HEADING.match(line) if in_fence is None else None
        if m:
            if current is not None:
                found[current] = "\n".join(buf)
            current, buf = int(m.group(1)), []
            order.append(current)
            continue
        if current is not None:
            buf.append(line)
    if current is not None:
        found[current] = "\n".join(buf)
    return found, order


def label_value(body, label):
    m = re.search(rf"\*\*{re.escape(label)}:?\*\*:?\s*(.*)", body or "")
    return m.group(1).strip() if m else None


def fenced_after(body, label):
    """The first fenced block after a line containing **label:**."""
    lines = (body or "").splitlines()
    start = None
    for i, line in enumerate(lines):
        if f"**{label}:**" in line:
            start = i + 1
            break
    if start is None:
        return None
    for i in range(start, len(lines)):
        stripped = lines[i].strip()
        if not stripped:
            continue
        opening = FENCE.match(stripped)
        if not opening:
            return None
        mark = opening.group(1)
        out = []
        for j in range(i + 1, len(lines)):
            s = lines[j].strip()
            if s and s[0] == mark[0] and set(s) == {mark[0]} and len(s) >= len(mark):
                return "\n".join(out)
            out.append(lines[j])
        return "\n".join(out)
    return None


def split_sub(body, pattern):
    """{ID: text} for `### <ID> …` sub-headings outside code blocks."""
    parts, current, buf, in_fence = {}, None, [], None
    for line in (body or "").splitlines():
        fence = FENCE.match(line.strip())
        if fence:
            mark = fence.group(1)
            if in_fence is None:
                in_fence = mark
            elif mark[0] == in_fence[0] and line.strip() == mark:
                in_fence = None
        m = re.match(rf"^###\s+({pattern})\b", line) if in_fence is None else None
        if m:
            if current:
                parts[current] = "\n".join(buf)
            current, buf = m.group(1).upper(), []
            continue
        if current:
            buf.append(line)
    if current:
        parts[current] = "\n".join(buf)
    return parts


def meta(block, name):
    m = re.search(rf"^\s*[-*]?\s*\*\*{name}:\*\*\s*(.*)$", block, re.MULTILINE)
    return m.group(1).strip() if m else ""


def table(body, heading=None):
    """Data rows of the first markdown table in `body` (after `### heading`, if given)."""
    lines = (body or "").splitlines()
    start = 0
    if heading:
        start = None
        for i, line in enumerate(lines):
            if re.match(rf"^###\s+{heading}\b", line, re.IGNORECASE):
                start = i + 1
                break
        if start is None:
            return None
    rows, seen = [], False
    for line in lines[start:]:
        s = line.strip()
        if heading and s.startswith("###"):
            break
        if not s.startswith("|"):
            if seen and s:
                break
            continue
        seen = True
        cells = [c.strip() for c in s.strip("|").split("|")]
        if all(re.fullmatch(r":?-{3,}:?", c) for c in cells if c):
            continue
        rows.append(cells)
    return rows[1:] if rows else []


def filled(cell, minimum=1):
    return (bool(cell) and not PLACEHOLDER.search(cell) and not re.fullmatch(r"\[.*\]", cell)
            and len(words(cell)) >= minimum)


def model_problem(value):
    v = (value or "").strip()
    if not v or PLACEHOLDER.search(v):
        return "left empty"
    if v.lower() == MODEL_HIDDEN:
        return None
    if v.lower() in BARE_TOOL_NAMES or not HAS_DIGIT.search(v):
        return f"{v!r} is a tool name, not a model — give the exact model and version, or write \"not displayed\""
    return None


# --------------------------------------------------------------------------- PlantUML


def puml_lines(src):
    """(lines, raw): comments blanked out, line numbers kept, so raw[i] can be inspected."""
    raw = (src or "").splitlines()
    out, in_block = [], False
    for line in raw:
        s = line
        if in_block:
            if "'/" in s:
                s, in_block = s.split("'/", 1)[1], False
            else:
                out.append("")
                continue
        if "/'" in s:
            before, after = s.split("/'", 1)
            if "'/" in after:
                s = before + after.split("'/", 1)[1]
            else:
                s, in_block = before, True
        if s.strip().startswith("'"):
            s = ""
        out.append(s)
    return out, raw


def is_puml(src):
    lines = [l.strip() for l in puml_lines(src)[0]]
    return any(l.startswith("@startuml") for l in lines) and any(l.startswith("@enduml") for l in lines)


def justified(raw, idx):
    """True if the nearest non-empty line above idx is a comment containing 'why:'."""
    j = idx - 1
    while j >= 0 and not raw[j].strip():
        j -= 1
    return j >= 0 and raw[j].strip().startswith("'") and "why:" in raw[j].lower()


PARTICIPANT = re.compile(
    r'^(?:create\s+)?(actor|participant|boundary|control|entity|database|collections|queue)\s+'
    r'(?:"([^"]+)"|([\w.:]+))(?:\s+as\s+(?:"([^"]+)"|([\w.]+)))?')
MESSAGE = re.compile(
    r'^("[^"]+"|[\w.:]+|\[|\])\s*'
    r'([<xo/\\]*-+(?:\[[^\]]*\])?-*[>xo/\\]*)\s*'
    r'("[^"]+"|[\w.:]+|\[|\])\s*(?:[+\-*!]{2}\s*)*(?::\s*(.*))?$')


def parse_sequence(src):
    lines, _ = puml_lines(src)
    participants = {}     # key -> display
    events = []           # dicts in file order: kind, line, label, frm, to, enclosing
    branches = []         # dicts: kind, guard, line
    stack = []            # current branch index of each open block
    i = 0
    while i < len(lines):
        s = lines[i].strip()
        i += 1
        if not s:
            continue
        m = PARTICIPANT.match(s)
        if m:
            if m.group(4):                       # participant Key as "Display"
                k, display = m.group(2) or m.group(3), m.group(4)
            else:
                display = m.group(2) or m.group(3)
                k = m.group(5) or display
            participants[k] = display
            participants.setdefault(display, display)
            if s.startswith("create"):
                events.append({"kind": "create", "line": i - 1, "label": "create " + display,
                               "enclosing": tuple(stack)})
            continue
        m = re.match(r'^create\s+("[^"]+"|[\w.:]+)', s)
        if m:
            name = m.group(1).strip('"')
            participants.setdefault(name, name)
            events.append({"kind": "create", "line": i - 1, "label": "create " + name,
                           "enclosing": tuple(stack)})
            continue
        m = re.match(r'^(r|h)?note\b(.*)$', s, re.I)
        if m:
            rest = m.group(2)
            if ":" in rest:
                text = rest.split(":", 1)[1]
            else:
                buf = []
                while i < len(lines) and not re.match(r'^\s*end\s*(r|h)?note', lines[i], re.I):
                    buf.append(lines[i])
                    i += 1
                i += 1
                text = " ".join(buf)
            events.append({"kind": "note", "line": i - 1, "label": text, "enclosing": tuple(stack)})
            continue
        m = re.match(r'^ref\b(.*)$', s)
        if m:
            if ":" not in m.group(1):
                while i < len(lines) and not re.match(r'^\s*end\s*ref', lines[i]):
                    i += 1
                i += 1
            continue
        if re.match(r'^box\b', s) or re.match(r'^end\s*box', s):
            continue
        m = re.match(r'^(alt|opt|loop|group|critical|break|par)\b\s*(.*)$', s)
        if m:
            branches.append({"kind": m.group(1), "guard": m.group(2).strip(), "line": i - 1})
            stack.append(len(branches) - 1)
            events.append({"kind": "branch", "line": i - 1, "label": m.group(2),
                           "enclosing": tuple(stack)})
            continue
        m = re.match(r'^else\b\s*(.*)$', s)
        if m and stack:
            parent = branches[stack[-1]]["kind"].replace("-else", "")
            branches.append({"kind": parent + "-else", "guard": m.group(1).strip(), "line": i - 1})
            stack[-1] = len(branches) - 1
            events.append({"kind": "branch", "line": i - 1, "label": m.group(1),
                           "enclosing": tuple(stack)})
            continue
        if re.match(r'^end\b(\s+\w+)?$', s) and stack:
            stack.pop()
            continue
        m = re.match(r'^return\b\s*(.*)$', s)
        if m:
            events.append({"kind": "message", "line": i - 1, "label": m.group(1).strip(),
                           "frm": None, "to": None, "enclosing": tuple(stack)})
            continue
        m = MESSAGE.match(s)
        if m and re.search(r"[<>\\/]", m.group(2)):
            events.append({"kind": "message", "line": i - 1, "label": (m.group(4) or "").strip(),
                           "frm": m.group(1).strip('"'), "to": m.group(3).strip('"'),
                           "enclosing": tuple(stack)})
    return {"participants": participants, "events": events, "branches": branches}


def guard_text(guard):
    return NEGATED.sub(" ", (guard or "").strip().strip("[]"))


def rejection_kind(guard):
    g = guard_text(guard)
    if DUP.search(g):
        return "duplicate"
    if FULL.search(g):
        return "full"
    return None


CLASS_DECL = re.compile(
    r'^(?:abstract\s+class|abstract|class|entity|enum|interface|struct|record)\s+'
    r'(?:"([^"]+)"|([\w.]+))(?:\s+as\s+([\w.]+))?[^{]*(\{)?\s*(\})?')
CL_ARROW = r'([<*o#x+^]?\|?[-.]+(?:(?:left|right|up|down|le|ri|l|r|u|d)[-.]+)?\|?[>*o#x+^]?)'
RELATION = re.compile(r'^("?[\w.]+"?)\s*(?:"([^"]*)")?\s*' + CL_ARROW +
                      r'\s*(?:"([^"]*)")?\s*("?[\w.]+"?)\s*(?::\s*(.*))?$')


def parse_classes(src):
    lines, raw = puml_lines(src)
    classes, declared_at, aliases, relations, notes, note_aliases = {}, {}, {}, [], [], set()
    current = None
    i = 0
    while i < len(lines):
        s = lines[i].strip()
        idx = i
        i += 1
        if not s:
            continue
        if current is not None:
            if s.startswith("}"):
                current = None
            else:
                classes[current].append(s)
            continue
        m = re.match(r'^note\b(.*)$', s, re.I)
        if m:
            rest = m.group(1)
            q = re.match(r'^\s*"([^"]*)"\s*(?:as\s+(\w+))?', rest)
            if q:
                notes.append(q.group(1))
                if q.group(2):
                    note_aliases.add(q.group(2))
            elif ":" in rest:
                notes.append(rest.split(":", 1)[1])
            else:
                a = re.search(r'\bas\s+(\w+)\s*$', rest)
                if a:
                    note_aliases.add(a.group(1))
                buf = []
                while i < len(lines) and not re.match(r'^\s*end\s*note', lines[i], re.I):
                    buf.append(lines[i])
                    i += 1
                i += 1
                notes.append(" ".join(buf))
            continue
        m = CLASS_DECL.match(s)
        if m:
            name = m.group(1) or m.group(2)
            classes.setdefault(name, [])
            declared_at.setdefault(name, idx)
            if m.group(3):
                aliases[m.group(3)] = name
            if m.group(4) and not m.group(5):
                current = name
            continue
        m = RELATION.match(s)
        if m and ("-" in m.group(3) or "." in m.group(3)):
            left = aliases.get(m.group(1).strip('"'), m.group(1).strip('"'))
            right = aliases.get(m.group(5).strip('"'), m.group(5).strip('"'))
            if left in note_aliases or right in note_aliases:
                continue
            relations.append({"left": left, "lm": (m.group(2) or "").strip(), "arrow": m.group(3),
                              "rm": (m.group(4) or "").strip(), "right": right,
                              "label": m.group(6) or "", "line": idx})
            for name in (left, right):
                classes.setdefault(name, [])
                declared_at.setdefault(name, idx)
            continue
        m = re.match(r'^([\w.]+)\s*:\s*(.+)$', s)          # Class : attribute
        if m and m.group(1) in classes:
            classes[m.group(1)].append(m.group(2))
    return {"classes": classes, "declared_at": declared_at, "relations": relations,
            "notes": notes, "raw": raw}


def associations(cl):
    """Plain associations: solid lines, not inheritance or realization."""
    return [r for r in cl["relations"] if "|" not in r["arrow"] and "^" not in r["arrow"]
            and "." not in r["arrow"]]


# --------------------------------------------------------------------------- results


class Results:
    def __init__(self):
        self.rows = []

    def add(self, cid, verdict, message):
        self.rows.append({"id": cid, "verdict": verdict, "message": message})

    def counts(self):
        out = {"PASS": 0, "FAIL": 0, "ERROR": 0}
        for r in self.rows:
            out[r["verdict"]] += 1
        return out


ALL_IDS = (
    ("S1", "all thirteen numbered sections present, in order"),
    ("S2", "no template markers left"),
    ("W1", "modeling explanation word count"),
    ("W2", "reflection word count"),
    ("A1", "Appendix A: scope and initial assumptions written before AI"),
    ("Q1", "user stories US-01 to US-03"),
    ("Q2", "acceptance criteria AC-01 to AC-06 in Given / When / Then"),
    ("Q3", "two criteria under each story"),
    ("Q4", "every criterion mapped to R1-R5, every rule covered"),
    ("Q5", "nothing out of scope in the stories and criteria"),
    ("SQ1", "every participant declared, every message named"),
    ("SQ2", "catalog browsing, then the registration request"),
    ("SQ3", "guarded success, full-course and duplicate alternatives"),
    ("SQ4", "duplicate and capacity checks between request and creation"),
    ("SQ5", "confirmation only after creation"),
    ("SQ6", "rejection paths create, change and confirm nothing"),
    ("SQ7", "rejection paths return the reason"),
    ("SQ8", "the atomic operation is stated"),
    ("CL1", "Student, Course, CourseOffering and Enrollment"),
    ("CL2", "the attributes R1 and R2 need"),
    ("CL3", "multiplicities at both ends of every association"),
    ("CL4", "each Enrollment links one Student and one CourseOffering"),
    ("CL5", "capacity and uniqueness constraints stated"),
    ("CL6", "every extra class justified"),
    ("CN1", "lifelines are classes, or explained in section 3"),
    ("CN2", "every association read both ways in section 4"),
    ("F1", "the AI's original diagrams kept"),
    ("F2", "four rendered images"),
    ("F3", "image links in sections 3, 4 and 12 resolve"),
    ("T1", "traceability covers R1-R5"),
    ("T2", "walkthroughs T1-T4 with path, verdict and location"),
    ("T3", "three review decisions with reasons"),
    ("T4", "two source checks with exact locators"),
    ("R1", "references"),
    ("E1", "four exchanges present"),
    ("E2", "exchange metadata"),
    ("E3", "prompts and responses complete"),
    ("E4", "Prompts A-D used as given"),
    ("E5", "bracketed fields replaced in Prompts A and D"),
    ("E6", "Prompt A carries the rules and your assumptions"),
    ("E7", "Prompt B carries the approved stories and criteria"),
    ("E8", "the originals are Prompt B's output, unedited"),
    ("E9", "Prompt C carries both diagrams"),
    ("E10", "Prompt D carries the original sources"),
)


# --------------------------------------------------------------------------- report checks


def check_requirements(res, measured, body):
    if body is None:
        for cid in ("Q1", "Q2", "Q3", "Q4", "Q5"):
            res.add(cid, "ERROR", "section 2 is missing")
        return
    stories = split_sub(body, r"US-\d+")

    # Q1 — three stories, each with its statement
    good, probs = [], []
    for sid in STORIES:
        text = label_value(stories.get(sid, ""), sid)
        if sid not in stories:
            probs.append(f"{sid} heading missing")
        elif not text or PLACEHOLDER.search(text) or len(words(text)) < 8:
            probs.append(f"{sid} statement empty or under 8 words")
        else:
            good.append(sid)
    measured["stories"] = len(good)
    res.add("Q1", "FAIL" if probs else "PASS",
            "; ".join(probs) if probs else "US-01, US-02 and US-03 written")

    # The criteria: one bullet each, `- **AC-0N** (Rn): Given … When … Then …`
    found = {}            # AC id -> (story, text)
    for sid, block in stories.items():
        current, buf = None, []
        for line in block.splitlines() + [""]:
            m = re.match(r"^\s*[-*]\s+\**\s*(AC-\d+)", line)
            if m or not line.strip():
                if current:
                    found.setdefault(current, (sid, " ".join(buf)))
                current, buf = (m.group(1).upper(), [line]) if m else (None, [])
            elif current:
                buf.append(line)

    gwt_ok, probs = [], []
    for cid in CRITERIA:
        if cid not in found:
            probs.append(f"{cid} missing")
            continue
        text = found[cid][1]
        if PLACEHOLDER.search(text):
            probs.append(f"{cid} not filled")
            continue
        lost = [w for w in ("Given", "When", "Then") if not re.search(rf"\b{w}\b", text, re.I)]
        if lost:
            probs.append(f"{cid} has no {'/'.join(lost)}")
        else:
            gwt_ok.append(cid)
    measured["criteria"] = len(gwt_ok)
    res.add("Q2", "FAIL" if probs else "PASS",
            "; ".join(probs) if probs else "AC-01 to AC-06 each have Given, When and Then")

    per_story = {sid: sorted(c for c, (s, _) in found.items() if s == sid) for sid in STORIES}
    bad = [f"{sid} has {len(per_story[sid])}" for sid in STORIES if len(per_story[sid]) != 2]
    res.add("Q3", "FAIL" if bad else "PASS",
            "two criteria per story required — " + ", ".join(bad) if bad
            else "two criteria under each story")

    unmapped, covered = [], set()
    for cid in CRITERIA:
        if cid not in found:
            continue
        ids = set(re.findall(r"\bR(\d+)\b", found[cid][1]))
        valid = {f"R{n}" for n in ids if f"R{n}" in RULES}
        if not valid or len(valid) != len(ids):
            unmapped.append(cid)
        covered |= valid
    uncovered = [r for r in RULES if r not in covered]
    probs = ([f"{', '.join(unmapped)} name(s) no rule, or a rule outside R1-R5"] if unmapped else []) \
        + ([f"no criterion maps to {', '.join(uncovered)}"] if uncovered else [])
    res.add("Q4", "FAIL" if probs else "PASS",
            "; ".join(probs) if probs else "every criterion names its rules; R1-R5 all covered")

    text = norm(body)
    hits = [name for name, pattern in EXCLUDED if re.search(pattern, text, re.I)]
    res.add("Q5", "FAIL" if hits else "PASS",
            "section 2 mentions excluded feature(s): " + ", ".join(hits)
            + " — remove them; say they are out of scope in section 1" if hits
            else "none of the five excluded features in the stories or criteria")


def check_sequence(res, src, path_note):
    ids = ("SQ1", "SQ2", "SQ3", "SQ4", "SQ5", "SQ6", "SQ7", "SQ8")
    if src is None or not is_puml(src):
        why = path_note or ("models/sequence.puml not found" if src is None
                            else "models/sequence.puml has no @startuml / @enduml")
        for cid in ids:
            res.add(cid, "ERROR", why)
        return None
    sq = parse_sequence(src)
    events, branches = sq["events"], sq["branches"]
    messages = [e for e in events if e["kind"] == "message"]
    declared = {key(k) for k in sq["participants"]}

    # SQ1
    probs = []
    if len({v for v in sq["participants"].values()}) < 3:
        probs.append("fewer than 3 participants declared")
    undeclared = sorted({e for m in messages for e in (m["frm"], m["to"])
                         if e and e not in "[]" and key(e) not in declared})
    if undeclared:
        probs.append("used but never declared: " + ", ".join(undeclared))
    unlabeled = [m for m in messages if not m["label"]]
    if unlabeled:
        probs.append(f"{len(unlabeled)} message(s) without a name")
    if not messages:
        probs.append("no messages")
    res.add("SQ1", "FAIL" if probs else "PASS",
            "; ".join(probs) if probs else
            f"{len(set(sq['participants'].values()))} participants declared, {len(messages)} messages, all named")

    creates = [e for e in events if e["kind"] == "create" or
               (e["kind"] == "message" and CREATE.search(e["label"]))]
    first_create = creates[0]["line"] if creates else None

    # SQ2
    catalog = next((m for m in messages if CATALOG.search(m["label"])), None)
    request = next((m for m in messages if catalog and m["line"] > catalog["line"]
                    and REQUEST.search(m["label"]) and not CREATE.search(m["label"])), None)
    if catalog is None:
        res.add("SQ2", "FAIL", "no catalog browsing — a message naming the catalog or the offerings (R1)")
    elif request is None:
        res.add("SQ2", "FAIL", "no registration request after the catalog — a message naming register / enrol")
    else:
        res.add("SQ2", "PASS", f"catalog \"{catalog['label'][:40]}\" then request \"{request['label'][:40]}\"")

    # SQ3
    alts = [b for b in branches if b["kind"] in ("alt", "alt-else")]
    unguarded = [b for b in alts if not b["guard"].strip("[] ")]
    kinds = [rejection_kind(b["guard"]) for b in alts]
    success = [b for b, k in zip(alts, kinds) if k is None and b["guard"].strip("[] ")]
    probs = []
    if len(alts) < 3:
        probs.append(f"{len(alts)} alt branch(es); success, full and duplicate need 3")
    if unguarded:
        probs.append(f"{len(unguarded)} alt/else branch(es) with no [guard]")
    if "full" not in kinds:
        probs.append("no branch guarded as full (e.g. [course full])")
    if "duplicate" not in kinds:
        probs.append("no branch guarded as duplicate (e.g. [already enrolled])")
    if not success:
        probs.append("no guarded success branch")
    res.add("SQ3", "FAIL" if probs else "PASS",
            "; ".join(probs) if probs else
            f"{len(alts)} guarded alt branches: success, full and duplicate")

    # SQ4
    if first_create is None:
        res.add("SQ4", "FAIL", "no message creates the Enrollment (create / insert / save)")
    elif request is None:
        res.add("SQ4", "FAIL", "no registration request to check after (see SQ2)")
    else:
        window = [e for e in events if request["line"] < e["line"] <= first_create]
        def seen(pattern):
            return any(pattern.search(e["label"] or "") for e in window)
        missing = [n for n, p in (("duplicate", DUP_CHECK), ("capacity", CAPACITY_CHECK)) if not seen(p)]
        res.add("SQ4", "FAIL" if missing else "PASS",
                "no " + " or ".join(missing) + " check between the registration request and the "
                "creation of the Enrollment (R2, R3 — the catalog view does not count)" if missing
                else "duplicate and capacity checked after the request, before creation")

    # SQ5
    confirms = [m for m in messages if CONFIRM.search(m["label"])]
    if not confirms:
        res.add("SQ5", "FAIL", "no confirmation message (R4) — name it with the word confirm")
    elif first_create is None:
        res.add("SQ5", "FAIL", "a confirmation, but nothing is created before it")
    else:
        early = [m for m in confirms if m["line"] < first_create]
        res.add("SQ5", "FAIL" if early else "PASS",
                f"confirmation \"{early[0]['label'][:40]}\" comes before the Enrollment is created (R4)"
                if early else "confirmation follows creation")

    # SQ6, SQ7
    rejecting = {}
    for i, b in enumerate(branches):
        kind = rejection_kind(b["guard"]) if b["kind"].startswith("alt") else None
        if kind:
            rejecting[i] = kind
    leaks, returned = [], {"full": False, "duplicate": False}
    for e in events:
        inside = [rejecting[i] for i in e["enclosing"] if i in rejecting]
        if not inside or e["kind"] not in ("message", "create"):
            continue
        label = e["label"] or ""
        if e["kind"] == "create" or CREATE.search(label) or STATE.search(label) or CONFIRM.search(label):
            leaks.append(label[:40])
        reason = inside[-1]
        if reason == "full" and re.search(r"\bfull\b", label, re.I):
            returned["full"] = True
        if reason == "duplicate" and (DUP.search(label) or re.search(r"enrolled", label, re.I)):
            returned["duplicate"] = True
    if not rejecting:
        res.add("SQ6", "FAIL", "no rejection branch to inspect (see SQ3)")
        res.add("SQ7", "FAIL", "no rejection branch to inspect (see SQ3)")
    else:
        res.add("SQ6", "FAIL" if leaks else "PASS",
                "a rejection branch creates, updates or confirms: " + "; ".join(leaks) if leaks
                else "rejection branches create, update and confirm nothing (R5)")
        kinds_present = set(rejecting.values())
        missing = [k for k in ("full", "duplicate") if k not in kinds_present or not returned[k]]
        res.add("SQ7", "FAIL" if missing else "PASS",
                "no message returns the reason on the " + " / ".join(missing)
                + " branch — R5 says explain \"course full\" or \"already enrolled\"" if missing
                else "each rejection branch returns its reason")

    # SQ8
    texts = [e["label"] for e in events if e["kind"] in ("note", "branch")]
    critical = any(b["kind"] == "critical" for b in branches)
    ok = critical or any(ATOMIC.search(t or "") for t in texts)
    res.add("SQ8", "PASS" if ok else "FAIL",
            "the atomic operation is stated" if ok
            else "no note or group states that the final checks and creation are one atomic operation")
    return sq


def check_classes(res, src, path_note):
    ids = ("CL1", "CL2", "CL3", "CL4", "CL5", "CL6")
    if src is None or not is_puml(src):
        why = path_note or ("models/classes.puml not found" if src is None
                            else "models/classes.puml has no @startuml / @enduml")
        for cid in ids:
            res.add(cid, "ERROR", why)
        return None
    cl = parse_classes(src)
    cmap = {key(k): k for k in cl["classes"]}

    missing = [c for c in REQUIRED_CLASSES if key(c) not in cmap]
    res.add("CL1", "FAIL" if missing else "PASS",
            "missing class(es): " + ", ".join(missing) + " — these four names are required, spelled this way"
            if missing else "Student, Course, CourseOffering and Enrollment present")

    def members(name):
        return [key(x) for x in cl["classes"].get(cmap.get(key(name), ""), [])]

    probs = []
    if not any("code" in m for m in members("Course")):
        probs.append("Course has no code (R1)")
    if not any("title" in m or "name" in m for m in members("Course")):
        probs.append("Course has no title (R1)")
    if not any("semester" in m or "term" in m for m in members("CourseOffering")):
        probs.append("CourseOffering has no semester (R1)")
    if not any("capacity" in m for m in members("CourseOffering")):
        probs.append("CourseOffering has no capacity (R2)")
    if not any("id" in m or "number" in m for m in members("Student")):
        probs.append("Student has no identifier")
    res.add("CL2", "FAIL" if probs else "PASS",
            "; ".join(probs) if probs else "code, title, semester, capacity and a student identifier present")

    assoc = associations(cl)
    no_mult = [f"{r['left']}-{r['right']}" for r in assoc if not r["lm"] or not r["rm"]]
    if not assoc:
        res.add("CL3", "FAIL", "no associations")
    else:
        res.add("CL3", "FAIL" if no_mult else "PASS",
                "association(s) without a multiplicity at both ends: " + ", ".join(no_mult) if no_mult
                else f"{len(assoc)} associations, multiplicities at both ends")

    def between(a, b):
        return [r for r in assoc if {key(r["left"]), key(r["right"])} == {key(a), key(b)}]

    probs = []
    for owner, part in (("Student", "Enrollment"), ("CourseOffering", "Enrollment"), ("Course", "CourseOffering")):
        rels = between(owner, part)
        if not rels:
            probs.append(f"no association {owner}-{part}")
            continue
        r = rels[0]
        owner_m, part_m = (r["lm"], r["rm"]) if key(r["left"]) == key(owner) else (r["rm"], r["lm"])
        if owner_m.replace(" ", "") != "1":
            probs.append(f"{owner} end of {owner}-{part} is {owner_m or 'empty'!s}, expected 1")
        if part != "CourseOffering" and not MANY.match(part_m.replace(" ", "")):
            probs.append(f"{part} end of {owner}-{part} is {part_m or 'empty'!s}, expected 0..* or *")
        if part == "CourseOffering" and not re.match(r"^(\*|[01]\.\.(\*|n))$", part_m.replace(" ", "")):
            probs.append(f"CourseOffering end of Course-CourseOffering is {part_m or 'empty'!s}, expected 0..* or 1..*")
    res.add("CL4", "FAIL" if probs else "PASS",
            "; ".join(probs) if probs else
            "1 Student and 1 CourseOffering per Enrollment, 0..* each way; 1 Course per CourseOffering")

    notes = norm(" ".join(cl["notes"]))
    braces = norm(" ".join(re.findall(r"\{[^}]*\}", " ".join(" ".join(v) for v in cl["classes"].values()))))
    text = notes + " " + braces
    cap = re.search(r"capacity", text)
    uniq = re.search(r"unique|at most one|duplicate|one enrol", text)
    probs = [x for x, ok in (("capacity", cap), ("uniqueness", uniq)) if not ok]
    res.add("CL5", "FAIL" if probs else "PASS",
            "no note states the " + " or the ".join(probs) + " constraint — multiplicity alone cannot express it"
            if probs else "capacity and uniqueness constraints stated in notes")

    extra = [c for c in cl["classes"] if key(c) not in {key(x) for x in REQUIRED_CLASSES}]
    unjust = [c for c in extra if not justified(cl["raw"], cl["declared_at"].get(c, 0))]
    res.add("CL6", "FAIL" if unjust else "PASS",
            "extra class(es) without a ' why: comment on the line above: " + ", ".join(sorted(unjust))
            if unjust else (f"{len(extra)} extra class(es), each with a ' why:" if extra else "no extra classes"))
    return cl


def image_links(body):
    return IMAGE.findall(COMMENT.sub("", body or ""))


def check_files(res, sections):
    # F1 — the AI's originals
    probs = []
    for stem in ("sequence", "classes"):
        path = os.path.join(ORIGINAL, stem + ".puml")
        if not os.path.isfile(path):
            hint = " (found original/class.puml — the name is classes.puml)" if stem == "classes" and \
                os.path.isfile(os.path.join(ORIGINAL, "class.puml")) else ""
            probs.append(f"models/original/{stem}.puml missing{hint}")
        elif not is_puml(read(path)):
            probs.append(f"models/original/{stem}.puml has no @startuml / @enduml")
    res.add("F1", "FAIL" if probs else "PASS",
            "; ".join(probs) if probs else "both original AI diagrams kept in models/original/")

    # F2 — renders
    have = os.listdir(IMG) if os.path.isdir(IMG) else []
    missing = []
    for stem in ("sequence", "classes", "original-sequence", "original-classes"):
        hit = [f for f in have if os.path.splitext(f)[0] == stem and f.lower().endswith((".png", ".svg"))
               and os.path.getsize(os.path.join(IMG, f)) > 0]
        if not hit:
            missing.append(f"img/{stem}.png|svg")
    res.add("F2", "FAIL" if missing else "PASS",
            "missing render(s): " + ", ".join(missing) if missing else "four renders in models/img/")

    # F3 — the images are embedded where the report needs them
    wanted = {3: ("sequence",), 4: ("classes",), 12: ("original-sequence", "original-classes")}
    probs = []
    for n, stems in wanted.items():
        if sections.get(n) is None:
            probs.append(f"section {n} missing")
            continue
        links = image_links(sections[n])
        for stem in stems:
            link = next((l for l in links if os.path.splitext(os.path.basename(l))[0] == stem), None)
            if link is None:
                probs.append(f"section {n} has no image link to img/{stem}")
            elif re.match(r"^https?://", link) or not os.path.isfile(os.path.normpath(link)):
                probs.append(f"section {n}: {link} does not resolve to a file in this folder")
    res.add("F3", "FAIL" if probs else "PASS",
            "; ".join(probs) if probs else "every image link in sections 3, 4 and 12 resolves")


def check_tables(res, measured, s):
    # T1 traceability
    if s.get(5) is None:
        res.add("T1", "ERROR", "section 5 is missing")
    else:
        rows = table(s[5]) or []
        covered, probs = set(), []
        for r in rows:
            if len(r) < 3:
                continue
            rule = re.findall(r"\bR([1-5])\b", r[0])
            if not rule or PLACEHOLDER.search(" ".join(r)):
                continue
            row = f"R{rule[0]}"
            if not re.search(r"\bAC-0[1-6]\b", r[0]):
                probs.append(f"{row} row names no AC-ID")
            elif not filled(r[1], 3):
                probs.append(f"{row} row has no model evidence")
            elif not filled(r[2], 1):
                probs.append(f"{row} row has no T-ID or extra check")
            else:
                covered |= {f"R{x}" for x in rule}
        missing = [r for r in RULES if r not in covered]
        res.add("T1", "FAIL" if missing or probs else "PASS",
                "; ".join(probs + ([f"no complete row for {', '.join(missing)}"] if missing else []))
                if missing or probs else "R1-R5 each traced to a criterion, model evidence and a case")

    # T2 walkthroughs
    walk = {c: None for c in CASES}
    if s.get(6) is None:
        res.add("T2", "ERROR", "section 6 is missing")
    else:
        rows = table(s[6]) or []
        probs = []
        for case in CASES:
            r = next((r for r in rows if r and re.match(rf"^\**{case}\b", r[0])), None)
            if r is None or len(r) < 3:
                probs.append(f"{case} row missing")
                continue
            verdict = re.match(r"^\W*(pass|fail)\b(.*)$", r[2], re.I)
            if verdict:
                walk[case] = verdict.group(1).lower()     # declared in submission.yml, even if T2 FAILs
            if not filled(r[1], 10):
                probs.append(f"{case} path empty or under 10 words")
            elif not verdict:
                probs.append(f"{case} judgment does not start with Pass or Fail")
            elif len(words(verdict.group(2))) < 3:
                probs.append(f"{case} gives a verdict with no location")
        measured["walkthroughs"] = walk
        res.add("T2", "FAIL" if probs else "PASS",
                "; ".join(probs) if probs else
                "T1-T4: " + ", ".join(f"{c} {v}" for c, v in walk.items()))

    # T3 review decisions
    if s.get(7) is None:
        res.add("T3", "ERROR", "section 7 is missing")
    else:
        rows = table(s[7]) or []
        good, probs = 0, []
        for i, r in enumerate(rows, 1):
            if len(r) < 4 or not any(filled(c) for c in r[:4]):
                continue
            if not all(filled(c) for c in r[:4]):
                probs.append(f"row {i}: a cell is empty")
            elif not re.search(r"\bR[1-5]\b", r[3]):
                probs.append(f"row {i}: rule is not one of R1-R5")
            elif len(words(r[2])) < 8:
                probs.append(f"row {i}: reason under 8 words")
            else:
                good += 1
        measured["review_decisions"] = good
        res.add("T3", "PASS" if good >= 3 else "FAIL",
                f"{good} complete review decision(s), 3 required" + (" — " + "; ".join(probs) if probs else ""))

    # T4 source checks, R1 references
    body = s.get(13)
    checks = table(body, "Source checks") if body is not None else None
    if checks is None:
        res.add("T4", "ERROR", "section 13 or its ### Source checks heading is missing")
    else:
        complete = [r for r in checks if len(r) >= 4 and all(filled(c) for c in r[:4])]
        measured["source_checks"] = len(complete)
        probs = []
        for i, r in enumerate(complete, 1):
            if not LOCATOR.search(r[1]):
                probs.append(f"row {i} has no slide / page / section / chapter / figure / URL")
            elif URL.search(r[1]) and not ACCESS_DATE.search(r[1]):
                probs.append(f"row {i} gives a URL with no access date")
        if len(complete) < 2:
            probs.insert(0, f"{len(complete)} complete row(s), 2 required")
        res.add("T4", "FAIL" if probs else "PASS",
                "; ".join(probs) if probs else f"{len(complete)} source checks, every one with a locator")
    if body is None:
        res.add("R1", "ERROR", "section 13 is missing")
    else:
        part = re.split(r"^###\s+Source checks", body, flags=re.M | re.I)[0]
        refs = [l.strip()[2:] for l in part.splitlines() if l.strip().startswith(("- ", "* "))]
        refs = [r for r in refs if r and not PLACEHOLDER.search(r) and len(words(r)) >= 4]
        probs = [] if refs else ["no reference entries (one per line, starting with '- ')"]
        for u in URL.findall(" ".join(r[1] for r in (checks or []) if len(r) > 1)):
            if u.lower().rstrip(".,;") not in part.lower():
                probs.append(f"{u} is in the source checks but not in References")
        res.add("R1", "FAIL" if probs else "PASS",
                "; ".join(probs) if probs else f"{len(refs)} reference(s); every table URL listed")


def check_exchanges(res, measured, s, originals):
    ids = ("E1", "E2", "E3", "E4", "E5", "E6", "E7", "E8", "E9", "E10")
    if s.get(11) is None:
        for cid in ids:
            res.add(cid, "ERROR", "section 11 is missing")
        return
    ex = split_sub(s[11], r"B\d+")
    present = [e for e in EXCHANGES if e in ex]
    absent = [e for e in EXCHANGES if e not in ex]
    measured["exchanges"] = len(ex)
    res.add("E1", "FAIL" if absent else "PASS",
            f"exchanges found: {', '.join(sorted(ex)) or 'none'}"
            + (f" — missing {', '.join(absent)}" if absent else ""))
    if not present:
        for cid in ids[1:]:
            res.add(cid, "ERROR", "no exchanges to check")
        return

    prompts = {e: fenced_after(ex[e], "Prompt") for e in present}
    responses = {e: fenced_after(ex[e], "Response") for e in present}

    probs, models = [], []
    for e in present:
        block = ex[e]
        for name in ("Tool", "Model", "Date", "Purpose"):
            value = meta(block, name)
            if not value or PLACEHOLDER.search(value):
                probs.append(f"{e} {name} empty")
        mp = model_problem(meta(block, "Model"))
        if mp and "empty" not in mp:
            probs.append(f"{e} model: {mp}")
        models.append(meta(block, "Model"))
        d = meta(block, "Date")
        if d and not PLACEHOLDER.search(d):
            if not ISO_DATE.match(d):
                probs.append(f"{e} date {d!r} is not YYYY-MM-DD")
            else:
                try:
                    if date.fromisoformat(d).year != 2026:
                        probs.append(f"{e} date {d} is not in 2026")
                except ValueError:
                    probs.append(f"{e} date {d!r} is not a real date")
    measured["model"] = models[0] if models else None
    res.add("E2", "FAIL" if probs else "PASS",
            "metadata: " + ("; ".join(probs) if probs else "tool, model, date and purpose on every exchange"))

    probs = []
    for e in present:
        p, r = prompts[e], responses[e]
        if not p or PLACEHOLDER.search(p) or len(words(p)) < 20:
            probs.append(f"{e} prompt missing or under 20 words")
        if not r or PLACEHOLDER.search(r):
            probs.append(f"{e} response missing")
        elif len(words(r)) < MIN_RESPONSE_WORDS[e]:
            probs.append(f"{e} response {len(words(r))} words — paste it complete "
                         f"(at least {MIN_RESPONSE_WORDS[e]} expected)")
    res.add("E3", "FAIL" if probs else "PASS",
            "; ".join(probs) if probs else "every prompt and response pasted in full")

    probs = []
    for e in present:
        p = norm(prompts[e])
        lost = [a for a in ANCHORS[e] if a not in p]
        if lost:
            probs.append(f"{e} prompt lost {len(lost)} fixed phrase(s), e.g. \"{lost[0]}\"")
    res.add("E4", "FAIL" if probs else "PASS",
            "; ".join(probs) if probs else "Prompts A, B, C and D used as given")

    probs = []
    for e, fields in BRACKET_FIELDS.items():
        if e in present:
            left = [f for f in fields if f in norm(prompts[e])]
            if left:
                probs.append(f"{e} still contains {', '.join(left)}")
    res.add("E5", "FAIL" if probs else "PASS",
            "; ".join(probs) if probs else "every bracketed field replaced")

    # E6 — Prompt A carries the rules and the initial assumptions
    if "B1" not in present or s.get(10) is None:
        res.add("E6", "ERROR", "Prompt A or section 10 missing")
    else:
        pa = norm(prompts["B1"])
        lost = [n for n in RULE_NAMES if n not in pa] + [r for r in ("R2", "R3", "R4") if not re.search(rf"\b{r.lower()}\b", pa)]
        hit = len(content_words(s[10]) & content_words(pa))
        probs = ([f"the rules are not pasted ({', '.join(lost)} missing)"] if lost else []) \
            + ([f"only {hit} content word(s) from your Appendix A — paste your initial assumptions"] if hit < 4 else [])
        res.add("E6", "FAIL" if probs else "PASS",
                "; ".join(probs) if probs else f"rules R1-R5 pasted; {hit} words shared with Appendix A")

    # E7 — Prompt B carries the approved stories and criteria
    if "B2" not in present:
        res.add("E7", "ERROR", "Prompt B missing")
    else:
        pb = prompts["B2"] or ""
        lost = [i for i in STORIES + CRITERIA if i not in pb.upper()]
        res.add("E7", "FAIL" if lost else "PASS",
                "Prompt B does not contain " + ", ".join(lost) + " — paste the approved requirements below it"
                if lost else "Prompt B carries US-01-03 and AC-01-06")

    # E8 — the originals are what Prompt B returned
    if "B2" not in present:
        res.add("E8", "ERROR", "Prompt B missing")
    else:
        rb = responses["B2"] or ""
        probs = []
        if rb.count("@startuml") < 2:
            probs.append(f"the Prompt B response holds {rb.count('@startuml')} PlantUML block(s), 2 expected")
        for stem, src in originals.items():
            if src is None:
                probs.append(f"models/original/{stem}.puml missing")
                continue
            got = share(shingles(src), rb)
            if got < 0.6:
                probs.append(f"only {got:.0%} of original/{stem}.puml is in the Prompt B response "
                             f"— the original is the AI's output, unedited")
        res.add("E8", "FAIL" if probs else "PASS",
                "; ".join(probs) if probs else "both originals are in the Prompt B response")

    # E9 — Prompt C carries both diagrams
    if "B3" not in present:
        res.add("E9", "ERROR", "Prompt C missing")
    else:
        n = (prompts["B3"] or "").count("@startuml")
        res.add("E9", "PASS" if n >= 2 else "FAIL",
                f"Prompt C holds {n} PlantUML block(s)" + ("" if n >= 2 else ", 2 expected — paste both models below it"))

    # E10 — Prompt D carries the original sources
    if "B4" not in present:
        res.add("E10", "ERROR", "Prompt D missing")
    else:
        both = set()
        for src in originals.values():
            both |= shingles(src or "")
        got = share(both, prompts["B4"] or "")
        res.add("E10", "PASS" if both and got >= 0.3 else "FAIL",
                f"Prompt D contains {got:.0%} of the original sources (30%+ expected — "
                f"\"Original sources: [paste]\")")


def check(text):
    res, measured = Results(), {}
    s, order = split_sections(text)

    missing = [n for n in SECTIONS if n not in s]
    if missing:
        res.add("S1", "ERROR", "missing heading(s): " + ", ".join(f"## {n}. {SECTIONS[n]}" for n in missing)
                + " — restore them from the template")
    elif [n for n in order if n in SECTIONS] != sorted(SECTIONS):
        res.add("S1", "FAIL", f"sections out of order: {order}")
    else:
        res.add("S1", "PASS", "sections 1-13 present, in order")

    left = PLACEHOLDER.findall(COMMENT.sub("", text))
    res.add("S2", "FAIL" if left else "PASS",
            f"{len(left)} template marker(s) like '(write here)' still in report.md" if left
            else "no template markers left")

    for cid, n, (lo, hi), name in (("W1", 8, EXPLANATION, "explanation_words"),
                                   ("W2", 9, REFLECTION, "reflection_words")):
        if s.get(n) is None:
            res.add(cid, "ERROR", f"section {n} is missing")
            continue
        count = len(words(s[n]))
        measured[name] = count
        res.add(cid, "PASS" if lo <= count <= hi else "FAIL",
                f"section {n} ({SECTIONS[n]}): {count} words, range {lo}-{hi}")

    if s.get(10) is None:
        res.add("A1", "ERROR", "section 10 is missing")
    else:
        scope = label_value(s[10], "Scope") or ""
        items = re.findall(r"^\s*\d+[.)]\s+(.*)$", s[10], re.MULTILINE)
        good = [i for i in items if not PLACEHOLDER.search(i) and len(words(i)) >= 3]
        probs = []
        if PLACEHOLDER.search(scope) or len(words(scope)) < 15:
            probs.append("**Scope:** empty or under 15 words")
        if len(good) < 2:
            probs.append(f"{len(good)} numbered assumption(s) of 3+ words, 2 required")
        res.add("A1", "FAIL" if probs else "PASS",
                "; ".join(probs) if probs else f"scope statement and {len(good)} initial assumptions")

    check_requirements(res, measured, s.get(2))

    seq_src, cls_src = read(SEQUENCE), read(CLASSES)
    cls_note = None
    if cls_src is None and os.path.isfile(os.path.join(MODELS, "class.puml")):
        cls_note = "models/classes.puml not found — you have models/class.puml; the name is classes.puml"
    sq = check_sequence(res, seq_src, None)
    cl = check_classes(res, cls_src, cls_note)

    # CN1, CN2 — consistency between the two diagrams and the report
    if sq is None or cl is None:
        res.add("CN1", "ERROR", "a diagram is missing, cannot compare")
    elif s.get(3) is None:
        res.add("CN1", "ERROR", "section 3 is missing")
    else:
        classes = {key(c) for c in cl["classes"]}
        others = []
        for display in sorted(set(sq["participants"].values())):
            base = display.split(":")[-1].strip()
            if key(base) not in classes:
                others.append(base)
        unexplained = [o for o in others if key(o) not in key(s[3])]
        res.add("CN1", "FAIL" if unexplained else "PASS",
                "lifeline(s) neither in the class diagram nor named in section 3: " + ", ".join(unexplained)
                if unexplained else
                (f"{len(others)} technical lifeline(s), each named in section 3" if others
                 else "every lifeline is a class"))
    if cl is None:
        res.add("CN2", "ERROR", "models/classes.puml missing, nothing to read")
    elif s.get(4) is None:
        res.add("CN2", "ERROR", "section 4 is missing")
    else:
        n_assoc = len(associations(cl))
        rows = [r for r in (table(s[4]) or []) if len(r) >= 3 and filled(r[1], 3) and filled(r[2], 3)]
        res.add("CN2", "PASS" if n_assoc and len(rows) >= n_assoc else "FAIL",
                f"{len(rows)} association(s) read both ways in section 4, the diagram has {n_assoc}")

    check_files(res, s)
    check_tables(res, measured, s)
    originals = {stem: read(os.path.join(ORIGINAL, stem + ".puml")) for stem in ("sequence", "classes")}
    check_exchanges(res, measured, s, originals)

    order_ids = [cid for cid, _ in ALL_IDS]
    res.rows.sort(key=lambda r: order_ids.index(r["id"]))
    return res, measured


def all_error(message):
    res = Results()
    for cid, _ in ALL_IDS:
        res.add(cid, "ERROR", message)
    return res


# --------------------------------------------------------------------------- output


def print_human(res, path):
    print(f"SIS #02 checker — {path} and models/")
    print("Checks SHAPE, never QUALITY.\n")
    names = dict(ALL_IDS)
    for r in res.rows:
        print(f"  {r['verdict']:<5}  {r['id']:<4} {names.get(r['id'], '')}")
        print(f"                {r['message']}")
    c = res.counts()
    print()
    print("Record these three numbers in submission.yml under checker:, with the commit hash")
    print("from `git rev-parse --short HEAD` — the commit this run was made at.")
    print(f"SUMMARY pass={c['PASS']} fail={c['FAIL']} error={c['ERROR']}")


def main():
    parser = argparse.ArgumentParser(description="Structural checker for SIS #02")
    parser.add_argument("--json", action="store_true", help="machine-readable output")
    args = parser.parse_args()

    if not os.path.isdir("tests") and not os.path.exists(REPORT):
        msg = "run this from inside your sis-02/ folder:  cd sis-02 && python tests/check_sis.py"
        print(json.dumps({"ok": False, "error": msg}) if args.json else "ERROR: " + msg)
        return 3

    if not os.path.exists(REPORT):
        res, measured, code = all_error(f"{REPORT} not found"), {}, 2
    else:
        res, measured = check(read(REPORT))
        c = res.counts()
        code = 0 if c["FAIL"] == 0 and c["ERROR"] == 0 else 1

    c = res.counts()
    if args.json:
        print(json.dumps({"ok": code == 0, "counts": c, "total": sum(c.values()),
                          "rows": res.rows, "measured": measured}, ensure_ascii=False, indent=2))
    else:
        print_human(res, REPORT)
    return code


if __name__ == "__main__":
    sys.exit(main())
