#!/usr/bin/env python3
"""
validate_submission.py — checks sis-02/submission.yml.   DO NOT EDIT THIS FILE.

    cd sis-02
    python tests/validate_submission.py            # human-readable
    python tests/validate_submission.py --json     # machine-readable, for the grading pipeline

It checks SHAPE, never QUALITY: every value filled, the model named exactly, and every
number and verdict you declare matching what tests/check_sis.py measures right now.
It learns the number of checks by running the checker, so there is no constant to drift.

Verdicts:
    PASS   the field is present and correct
    FAIL   the field is present but wrong, or disagrees with report.md
    ERROR  the field is absent, or the checker could not be run

Exit codes: 0 = no FAIL and no ERROR · 1 = at least one FAIL or ERROR ·
            2 = submission.yml missing or unparseable · 3 = wrong working directory.

Standard library only. It reads the small subset of YAML that submission.yml uses and
refuses anything else with a line number.
"""

import argparse
import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
CHECKER = os.path.join(HERE, "check_sis.py")

STUDENT_ID = re.compile(r"^\d{2}[A-Za-z]\d{6}$")
GITHUB_LOGIN = re.compile(r"^[A-Za-z0-9](?:[A-Za-z0-9]|-(?=[A-Za-z0-9])){0,38}$")
SHORT_SHA = re.compile(r"^[0-9a-fA-F]{7,40}$")
CHECK_ID = re.compile(r"^[A-Z]{1,2}\d{1,2}$")
CASES = ("T1", "T2", "T3", "T4")
COUNTS = ("stories", "criteria", "exchanges", "review_decisions", "source_checks",
          "explanation_words", "reflection_words")
BARE_TOOL_NAMES = {
    "chatgpt", "gpt", "claude", "gemini", "copilot", "github copilot", "deepseek",
    "grok", "mistral", "llama", "qwen", "perplexity", "cursor", "openai", "anthropic",
}
MODEL_HIDDEN = "not displayed"
PLACEHOLDER = re.compile(r"(^<.*>$)|(\bTODO\b)|(\byour name\b)|(\bfill in\b)|(^\.\.\.$)", re.I)


# --------------------------------------------------------------------------- parsing


class ParseError(Exception):
    pass


def scalar(raw):
    v = raw.strip()
    if v.startswith("[") and v.endswith("]"):
        inner = v[1:-1].strip()
        return [x.strip().strip("'\"") for x in inner.split(",") if x.strip()] if inner else []
    if len(v) >= 2 and v[0] == v[-1] and v[0] in "'\"":
        return v[1:-1]
    return v


def strip_comment(line):
    out, quote = [], None
    for i, ch in enumerate(line):
        if ch in "'\"":
            quote = None if quote == ch else (ch if quote is None else quote)
        if ch == "#" and quote is None and (i == 0 or line[i - 1] in " \t"):
            break
        out.append(ch)
    return "".join(out).rstrip()


def parse(text):
    """Top-level `key: value`, `key:` + an indented map of `sub: value`, or `key:` + `- item`."""
    doc, parent = {}, None
    for n, raw in enumerate(text.splitlines(), 1):
        if "\t" in raw:
            raise ParseError(f"line {n}: a tab character — indent with two spaces")
        line = strip_comment(raw)
        if not line.strip():
            continue
        indent = len(line) - len(line.lstrip(" "))
        body = line.strip()
        if indent == 0:
            m = re.match(r"^([A-Za-z_][\w]*)\s*:\s*(.*)$", body)
            if not m:
                raise ParseError(f"line {n}: expected 'key: value', got {body!r}")
            key, value = m.group(1), m.group(2)
            if value == "":
                doc[key] = None
                parent = key
            else:
                doc[key] = scalar(value)
                parent = None
            continue
        if parent is None:
            raise ParseError(f"line {n}: indented line with no parent key above it")
        if body.startswith("- ") or body == "-":
            if doc[parent] is None:
                doc[parent] = []
            if not isinstance(doc[parent], list):
                raise ParseError(f"line {n}: '- item' under {parent}, which holds keys")
            doc[parent].append(scalar(body[1:]))
            continue
        m = re.match(r"^([A-Za-z_][\w]*)\s*:\s*(.*)$", body)
        if not m:
            raise ParseError(f"line {n}: expected 'subkey: value', got {body!r}")
        if doc[parent] is None:
            doc[parent] = {}
        if not isinstance(doc[parent], dict):
            raise ParseError(f"line {n}: 'subkey: value' under {parent}, which holds a list")
        doc[parent][m.group(1)] = scalar(m.group(2)) if m.group(2) else None
    return doc


def get(doc, dotted):
    node = doc
    for part in dotted.split("."):
        if not isinstance(node, dict) or part not in node:
            return KeyError
        node = node[part]
    return node


def as_int(v):
    if isinstance(v, str) and re.fullmatch(r"\d+", v.strip()):
        return int(v)
    return None


def empty(v):
    return v is None or v is KeyError or (isinstance(v, str) and (not v.strip() or PLACEHOLDER.search(v)))


# --------------------------------------------------------------------------- checks


class Report:
    def __init__(self):
        self.rows = []

    def add(self, cid, verdict, message):
        self.rows.append({"id": cid, "verdict": verdict, "message": message})

    def counts(self):
        out = {"PASS": 0, "FAIL": 0, "ERROR": 0}
        for r in self.rows:
            out[r["verdict"]] += 1
        return out

    def clean(self):
        c = self.counts()
        return c["FAIL"] == 0 and c["ERROR"] == 0


def text_field(rep, cid, doc, key, test=None):
    v = get(doc, key)
    if v is KeyError:
        rep.add(cid, "ERROR", f"{key}: the key is missing — restore it from the template")
    elif empty(v) or isinstance(v, list):
        rep.add(cid, "FAIL", f"{key}: left empty")
    else:
        problem = test(str(v)) if test else None
        rep.add(cid, "FAIL" if problem else "PASS", f"{key}: {problem or v}")
    return None if v is KeyError else v


def run_checker(folder):
    try:
        done = subprocess.run([sys.executable, CHECKER, "--json"],
                              cwd=folder, capture_output=True, text=True, timeout=60)
        parsed = json.loads(done.stdout)
        return parsed if parsed.get("counts") else None
    except (OSError, ValueError, subprocess.TimeoutExpired):
        return None


def validate(doc, folder):
    rep = Report()
    run = run_checker(folder)
    measured = (run or {}).get("measured") or {}
    now = (run or {}).get("counts")

    # D1 identity of the file
    ok = as_int(str(get(doc, "schema"))) == 1 and get(doc, "assignment") == "sis-02"
    rep.add("D1", "PASS" if ok else "FAIL",
            "schema 1, assignment sis-02" if ok else "schema must be 1 and assignment \"sis-02\" — do not edit these")

    # D2-D5 student
    text_field(rep, "D2", doc, "student.name")
    text_field(rep, "D3", doc, "student.student_id",
               lambda v: None if STUDENT_ID.match(v) else "does not look like a KBTU student ID (e.g. 00X000000)")
    text_field(rep, "D4", doc, "student.group")
    text_field(rep, "D5", doc, "student.github",
               lambda v: None if GITHUB_LOGIN.match(v) else "give the GitHub username only, not a URL")

    # D6-D7 assistant
    text_field(rep, "D6", doc, "assistant.tool")

    def model_problem(v):
        low = v.strip().lower()
        if low != MODEL_HIDDEN and (low in BARE_TOOL_NAMES or not re.search(r"\d", v)):
            return f"{v!r} is a tool name, not a model — give the exact model, or write: not displayed"
        rep_model = (measured.get("model") or "").strip().lower()
        if rep_model and rep_model != low:
            return f"{v!r} here, but exchange B1 in report.md says {measured.get('model')!r}"
        return None
    text_field(rep, "D7", doc, "assistant.model", model_problem)

    # D8-D10 checker numbers
    nums = {k: as_int(str(get(doc, f"checker.{k}"))) for k in ("pass", "fail", "error")}
    if run is None or now is None:
        rep.add("D8", "ERROR", "tests/check_sis.py could not be run — is it next to this file, unedited?")
        rep.add("D9", "ERROR", "no checker run to compare with")
    else:
        total = sum(now.values())
        if any(v is None for v in nums.values()):
            rep.add("D8", "FAIL", "checker.pass / fail / error must all be whole numbers")
            rep.add("D9", "FAIL", "nothing to compare")
        else:
            s = sum(nums.values())
            rep.add("D8", "PASS" if s == total else "FAIL",
                    f"pass + fail + error = {s}" + ("" if s == total else f", but the checker runs {total} checks"))
            same = (nums["pass"], nums["fail"], nums["error"]) == (now["PASS"], now["FAIL"], now["ERROR"])
            rep.add("D9", "PASS" if same else "FAIL",
                    f"declared {nums['pass']}/{nums['fail']}/{nums['error']}, a run now gives "
                    f"{now['PASS']}/{now['FAIL']}/{now['ERROR']}"
                    + ("" if same else " — re-run the checker and copy its numbers"))
    commit = get(doc, "checker.commit")
    if commit is KeyError:
        rep.add("D10", "ERROR", "checker.commit: the key is missing")
    elif empty(commit) or not SHORT_SHA.match(str(commit)):
        rep.add("D10", "FAIL", f"checker.commit must be a hash from git rev-parse --short HEAD, got {commit!r}")
    else:
        rep.add("D10", "PASS", f"checker.commit: {commit}")

    # D11 counts
    probs = []
    for k in COUNTS:
        declared = as_int(str(get(doc, f"counts.{k}")))
        actual = measured.get(k)
        if declared is None:
            probs.append(f"{k} empty or not a number")
        elif actual is None:
            probs.append(f"{k}: report.md gives nothing to measure")
        elif declared != actual:
            probs.append(f"{k}: declared {declared}, report.md has {actual}")
    rep.add("D11", "FAIL" if probs else "PASS", "counts: " + ("; ".join(probs) if probs else "all match report.md"))

    # D12 walkthrough verdicts
    walk = measured.get("walkthroughs") or {}
    probs = []
    for case in CASES:
        v = get(doc, f"walkthroughs.{case}")
        declared = str(v).strip().lower() if v not in (None, KeyError) else ""
        if declared not in ("pass", "fail"):
            probs.append(f"{case} must be pass or fail")
        elif not walk.get(case):
            probs.append(f"{case}: section 6 has no verdict to compare with")
        elif declared != walk[case]:
            probs.append(f"{case}: declared {declared}, section 6 says {walk[case]}")
    rep.add("D12", "FAIL" if probs else "PASS",
            "walkthroughs: " + ("; ".join(probs) if probs else "match section 6 — "
                                + ", ".join(f"{c} {walk[c]}" for c in CASES)))

    # D13 known_fails
    kf = get(doc, "known_fails")
    if kf is KeyError:
        rep.add("D13", "ERROR", "known_fails: the key is missing — write known_fails: [] if the checker is clean")
    elif not isinstance(kf, list):
        rep.add("D13", "FAIL", "known_fails must be a list, e.g. [W1, SQ8] or []")
    elif run is None:
        rep.add("D13", "ERROR", "no checker run to compare with")
    else:
        bad_ids = [x for x in kf if not CHECK_ID.match(str(x))]
        failing = sorted(r["id"] for r in run.get("rows", []) if r["verdict"] != "PASS")
        listed = sorted(set(str(x) for x in kf))
        if bad_ids:
            rep.add("D13", "FAIL", f"known_fails holds things that are not check IDs: {bad_ids}")
        elif listed != failing:
            rep.add("D13", "FAIL", f"known_fails lists {listed or '[]'}, the checker fails {failing or '[]'}")
        else:
            rep.add("D13", "PASS", f"known_fails matches the checker: {listed or '[]'}")
    return rep


# --------------------------------------------------------------------------- main


def main():
    parser = argparse.ArgumentParser(description="Validate sis-02/submission.yml")
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--file", default="submission.yml")
    args = parser.parse_args()

    if args.file == "submission.yml" and not os.path.exists("submission.yml") and not os.path.isdir("tests"):
        msg = "run this from inside your sis-02/ folder:  cd sis-02 && python tests/validate_submission.py"
        print(json.dumps({"ok": False, "error": msg}) if args.json else "ERROR: " + msg)
        return 3
    if not os.path.exists(args.file):
        msg = f"{args.file} not found — copy it from SIS_02.zip"
        print(json.dumps({"ok": False, "error": msg}) if args.json else "ERROR: " + msg)
        return 2
    try:
        doc = parse(open(args.file, encoding="utf-8").read())
    except ParseError as exc:
        print(json.dumps({"ok": False, "error": str(exc)}) if args.json else f"ERROR: {args.file}, {exc}")
        return 2

    folder = os.path.dirname(os.path.abspath(args.file))
    rep = validate(doc, folder)

    def val(key):
        v = get(doc, key)
        return None if v is KeyError else v

    if args.json:
        print(json.dumps({
            "ok": rep.clean(),
            "counts": rep.counts(),
            "rows": rep.rows,
            "declared": {
                "student_id": val("student.student_id"),
                "github": val("student.github"),
                "group": val("student.group"),
                "tool": val("assistant.tool"),
                "model": val("assistant.model"),
                "commit": val("checker.commit"),
                "checker": {k: as_int(str(val(f"checker.{k}"))) for k in ("pass", "fail", "error")},
                "counts": val("counts"),
                "walkthroughs": val("walkthroughs"),
                "known_fails": val("known_fails"),
            },
        }, ensure_ascii=False, indent=2))
    else:
        print(f"SIS #02 declaration — {args.file}\nChecks SHAPE, never QUALITY.\n")
        for r in rep.rows:
            print(f"  {r['verdict']:<5}  {r['id']:<4} {r['message']}")
        c = rep.counts()
        print(f"\nSUMMARY pass={c['PASS']} fail={c['FAIL']} error={c['ERROR']}")
    return 0 if rep.clean() else 1


if __name__ == "__main__":
    sys.exit(main())
